{"name": "test_payment_exception[caseinfo0]", "status": "broken", "statusDetails": {"message": "KeyError: 'field_name'", "trace": "self = <test_project.finance.TestFinance object at 0x0000027792405610>\ncaseinfo = {'new_income_flow': {'case_id': 'API001', 'data': {'comment': '1', 'content': '设计服务', 'invoice_id': '554', 'invoice_st...ntent': '设计服务', 'invoice_id': '554', 'invoice_state': 0, ...}, 'expected_result': 'None', 'is_positive': 'front', ...}}\n\n    @pytest.mark.parametrize('caseinfo',YamlUtil('./Conf/yaml/finance.yaml').read_yaml_excel('./api_test_case/finance.xlsx','payment_exception'))\n    def test_payment_exception(self,caseinfo):\n        global response\n        case_id = caseinfo['payment_exception']['case_id']\n        url = caseinfo['payment_exception']['url']\n        data = caseinfo['payment_exception']['data']\n        is_positive = caseinfo['payment_exception']['is_positive']\n        request_type = caseinfo['payment_exception']['request_type']\n        expected_result = caseinfo['payment_exception']['expected_result']\n        status_code = caseinfo['payment_exception']['status_code']\n>       field_name = caseinfo['payment_exception']['field_name']\nE       KeyError: 'field_name'\n\ntest_project\\finance.py:33: KeyError"}, "parameters": [{"name": "caseinfo", "value": "{'new_income_flow': {'case_id': 'API001', 'title': '付款异常', 'url': 'https://open-t.handyprint.cn/api/invoices/state', 'data': {'invoice_id': '554', 'invoice_state': 0, 'vendor_name': '抟力数智（宁波）科技有限公司', 'tax_rate': '1', 'content': '设计服务', 'comment': '1'}, 'is_positive': 'front', 'request_type': 'PUT', 'expected_result': 'None', 'status_code': 200, 'field_name': 'None'}, 'payment_exception': {'case_id': 'API001', 'title': '付款异常', 'url': 'https://open-t.handyprint.cn/api/invoices/state', 'data': {'invoice_id': '554', 'invoice_state': 0, 'vendor_name': '抟力数智（宁波）科技有限公司', 'tax_rate': '1', 'content': '设计服务', 'comment': '1'}, 'is_positive': 'front', 'request_type': 'PUT', 'expected_result': 'None', 'status_code': 200}}"}], "start": 1683618736674, "stop": 1683618736675, "uuid": "5fa41cf5-a501-4e40-a5dc-ccdcb17c12dd", "historyId": "89be1f884d039883296a87c0219e3207", "testCaseId": "e6d80fd88f8a8bf972fb3cb67578d144", "fullName": "test_project.finance.TestFinance#test_payment_exception", "labels": [{"name": "parentSuite", "value": "test_project"}, {"name": "suite", "value": "finance"}, {"name": "subSuite", "value": "TestFinance"}, {"name": "host", "value": "DESKTOP-MMPUN61"}, {"name": "thread", "value": "21936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_project.finance"}]}